title: Radosław Skupnik's blog
author: Radosław Skupnik
description: A blog on various topics related to programming

highlighter: null
permalink: /:title

url: http://github.com/rskupnik
baseurl:

sass:
  sass_dir: public/css
  style: :compressed